#! /usr/bin/env bash



# update
git pull

echo stopping website..
docker stop website
echo removing old container..
docker rm website

echo starting new version..
# run nginx
docker run --restart always -p 80:80 --name website -v /home/keeb/git/content/content/_site:/usr/share/nginx/html:ro -d nginx

