version: '3'
services:
  nginx:
    container_name: website
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./site/_site:/usr/share/nginx/html:ro
      - ./conf/certbot/conf:/etc/letsencrypt
      - ./conf/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    container_name: certificates
    image: certbot/certbot
    volumes:
      - ./conf/certbot/conf:/etc/letsencrypt
      - ./conf/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"