# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Hi, I'm Nick
tagline:          ''
description:      'I do lots of stuff; I write about it here'
url:              http://keeb.dev
baseurl:          /

author:
  name:           'Nick Stinemates'
  url:            https://twitter.com/nickstinemates

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/keeb-dev/content

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
